const actionTypes = {
  categoriesActions: {
    FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
    FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
    FETCH_CATEGORIES_FAIL: "FETCH_CATEGORIES_FAIL",
  },
  booksActions: {
    FETCH_BOOKS_START: "FETCH_BOOKS_START",
    FETCH_BOOKS_SUCCESS: "FETCH_BOOKS_SUCCESS",
    FETCH_BOOKS_FAIL: "FETCH_BOOKS_FAIL",
  },
};
export default actionTypes;
